- name: add backuppc to sudoers
  template:
    dest=/etc/sudoers.d/{{backuppc_user}}
    src=etc/sudoers.d/{{backuppc_user}}
    owner=root
    group=root
    mode=0440
    validate='visudo -cf %s'

- name: add /etc/sudoers.d include
  lineinfile:
    dest="/etc/sudoers"
    mode=0440
    validate='visudo -cf %s'
    line='#includedir /etc/sudoers.d'
    insertafter=EOF
